services:
  mysql:
    user: 501:20
    image: mysql:8.0.33
    ports:
      - 13306:3306
    volumes:
      - C:/leejunbum/docker/mysql_docker/data:/var/lib/mysql:rw
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: preonboarding
      MYSQL_DATABASE: wanted
